const works=window.seriesWorks||[],field=document.querySelector("#field"),dialog=document.querySelector("#reader");
let activeFilter="all",visible=works.slice(),active=0;
const filters=["all",...new Set(works.map(work=>work.group).filter(Boolean))];
document.querySelector(".filters").innerHTML=filters.map((filter,index)=>`<button class="${index===0?'active':''}" data-filter="${filter}">${filter==='all'?'All works':filter}</button>`).join("");
function render(){field.innerHTML=works.map((work,index)=>`<button class="work" data-index="${index}" style="--span:${work.span||4};--lift:${work.lift||0}rem"><span class="image-wrap"><img src="${work.image}" alt="${work.title}" loading="lazy"><span class="number">${String(index+1).padStart(2,'0')}</span></span><span class="caption"><strong>${work.title}${work.collected?'<i class="collection-dot" title="Private collection" aria-label="Private collection"></i>':''}</strong><span>${work.year}</span></span></button>`).join("");field.querySelectorAll(".work").forEach(button=>button.addEventListener("click",()=>open(works[+button.dataset.index])));filter()}
function filter(){visible=works.filter(work=>activeFilter==='all'||work.group===activeFilter);field.querySelectorAll(".work").forEach(button=>button.hidden=!visible.includes(works[+button.dataset.index]));document.querySelector(".count").textContent=`${String(visible.length).padStart(2,'0')} works`}
function open(work){active=visible.indexOf(work);update();dialog.showModal()}
function update(){const work=visible[active];dialog.querySelector("img").src=work.image;dialog.querySelector("img").alt=work.title;dialog.querySelector("h2").textContent=work.title;dialog.querySelector(".meta").textContent=work.meta;dialog.querySelector(".counter").textContent=`${String(active+1).padStart(2,'0')} / ${String(visible.length).padStart(2,'0')}`}
document.querySelector(".filters").addEventListener("click",event=>{if(!event.target.dataset.filter)return;activeFilter=event.target.dataset.filter;document.querySelectorAll(".filters button").forEach(button=>button.classList.toggle("active",button===event.target));filter()});
document.querySelectorAll("[data-mode]").forEach(button=>button.addEventListener("click",()=>{document.body.classList.toggle("index-view",button.dataset.mode==='index');document.querySelectorAll("[data-mode]").forEach(item=>item.classList.toggle("active",item===button))}));
dialog.querySelector(".close").addEventListener("click",()=>dialog.close());dialog.querySelectorAll("[data-nav]").forEach(button=>button.addEventListener("click",()=>{active=(active+(button.dataset.nav==='next'?1:-1)+visible.length)%visible.length;update()}));
dialog.addEventListener("click",event=>{if(event.target===dialog)dialog.close()});document.addEventListener("keydown",event=>{if(!dialog.open)return;if(event.key==='ArrowRight'){active=(active+1)%visible.length;update()}if(event.key==='ArrowLeft'){active=(active-1+visible.length)%visible.length;update()}});render();
